In [46]:
import numpy as np

## **Zadanie 1**

Stwórz tablicę numpy o wymiarach (4,4) wypełnioną wartościami od 2 do 32 z krokiem 2 i przypisz ją do zmiennej. Wyświetl jej:
* typ danch,
* liczbę elementów,
* wielkość pojedynczego elementu
* ilość zaalokowanej pamięci.



In [47]:
array = np.arange(2,33,2).reshape(4,4)
array

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [48]:
# Typ danych
array.dtype

dtype('int64')

In [49]:
# Liczba elementów
array.size

16

In [50]:
# Wielkość pojedynczego elementu
array.itemsize

8

In [51]:
# Ilość zaalokowanej pamięci
array.itemsize * array.size

128

## **Zadanie 2**

Zwróć tablicę z zadania 1 jako widok. Zmień jej typ danych (możesz to zrobić np. funkcją astype()) na np.uint8. Sprawdź teraz czy tablica jest widokiem czy kopią tablicy oryginalnej. Wyświetl jej
* liczbę elementów,
* wielkość pojedynczego elementu
* ilość zaalokowanej pamięci.

In [52]:
def get_data_base(x):
    base = x
    while isinstance(base.base, np.ndarray):
        base = base.base
    return base

def arrays_share_data(x, y):
    return get_data_base(x) is get_data_base(y)

In [53]:
array2 = array[:,:]
arrays_share_data(array2, array)


True

In [64]:
# Zmiana typu danych
array2 = array2.astype(dtype=np.uint8)
arrays_share_data(array2, array)

False

In [65]:
# Liczba elementów
array2.size

16

In [66]:
# Wielkość pojedynczego elementu
array2.itemsize

1

In [67]:
# Ilość zaalokowanej pamięci
array2.itemsize * array2.size

16

## **Zadanie 3**

Wytnij z tablicy z zadania 1 obszar 2 x 2 "ze środka" tablicy (wartości 12,14, 20,22) na dwa sposoby:

* jeden jako widok i przypisz do zmiennej
* drugi jako kopia i przypisz do zmiennej

Posługując się przykładami z zajęć sprawdź czy baza tych dwóch tablic jest różna (powinna być).

In [58]:
# Like View
array3 = array[1:3,1:3]
arrays_share_data(array3, array)

True

In [68]:
array3

array([[12, 14],
       [20, 22]])

In [60]:
# Like Copy
idx = [1,2]
array4 = array[idx,1:3]
arrays_share_data(array4, array)

False

In [69]:
array4

array([[12, 14],
       [20, 22]])

## **Zadanie 4**

Stwórz tablicę 4x4, która zawiera wartości 1,2,3,4 w każdym wierszu. Następnie wykorzystując funkcje łączenia tablic utwórz tablicę połączoną z powyższej tablicy i jej wersji lustrzanej w poziomie (spróbuj użyć wycinków).

In [61]:
# Option 1
array = np.tile(np.array([1, 2, 3, 4]), (4,1))
mirror_array = array[:,::-1]
combination = np.hstack((array, mirror_array))
combination

array([[1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1]])

In [70]:
# Option 2
combination = np.hstack((array, array[:,::-1]))
combination

array([[1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1]])

## **Zadanie 5**

Utwórz tablicę o nazwie Z_5 o wymiarach 2x2 wypełnioną wartościami 1. Wykorzystując funkcje łączenia tabel uwtórz tablicę, która finalnie będzie tablicą składającą się z 4-ech tablic Z_5, ale tak aby finalnie była to tablica 4 x 4 podobna do poniższej:

1,1,2,2

1,1,2,2

3,3,4,4

3,3,4,4

In [62]:
# Option 1
Z_5 = np.ones((2,2), dtype=int)
half_array = np.hstack((Z_5, Z_5+1))
final_array = np.vstack((half_array, half_array+2))
final_array

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [63]:
# Option 2
final_array = np.vstack((np.hstack((Z_5, Z_5 *2)), np.hstack((Z_5*3, Z_5 *4))))
final_array

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])