# Metody analizy danych. Lab 3. Biblioteka numpy, część 3

## 1. Wybrane operacje arytmetyczne na tablicy numpy

In [1]:
import numpy as np

In [43]:
# funkcje zaczerpnięte z https://tobiasraabe.github.io/post/numpy-views-vs-copies/
# dzięki nim łatwiej będzie nam interpretować czy dwie tablice numpy posiadają wspólną bazę
# co oznacza, że współdzielą pamięć (lub nie)

def get_data_base(x):
    base = x
    while isinstance(base.base, np.ndarray):
        base = base.base
    return base

def arrays_share_data(x, y):
    return get_data_base(x) is get_data_base(y)

In [28]:
arr = np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
# suma wartości elementów tablicy
print(arr.sum())
# lub
print(np.sum(arr))

5050
5050


In [34]:
# suma w kolumnach (indeks po wierszach)
print(arr.sum(axis=0))
# i w wierszach (indeks po kolumnach)
print(arr.sum(axis=1))

[460 470 480 490 500 510 520 530 540 550]
[ 55 155 255 355 455 555 655 755 855 955]


In [35]:
# suma skumulowana
print(arr.cumsum())

[   1    3    6   10   15   21   28   36   45   55   66   78   91  105
  120  136  153  171  190  210  231  253  276  300  325  351  378  406
  435  465  496  528  561  595  630  666  703  741  780  820  861  903
  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540 1596
 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415 2485
 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486 3570
 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753 4851
 4950 5050]


In [36]:
# i ponownie możemy wykonać operację dla danej osi
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 12  14  16  18  20  22  24  26  28  30]
 [ 33  36  39  42  45  48  51  54  57  60]
 [ 64  68  72  76  80  84  88  92  96 100]
 [105 110 115 120 125 130 135 140 145 150]
 [156 162 168 174 180 186 192 198 204 210]
 [217 224 231 238 245 252 259 266 273 280]
 [288 296 304 312 320 328 336 344 352 360]
 [369 378 387 396 405 414 423 432 441 450]
 [460 470 480 490 500 510 520 530 540 550]]
[[  1   3   6  10  15  21  28  36  45  55]
 [ 11  23  36  50  65  81  98 116 135 155]
 [ 21  43  66  90 115 141 168 196 225 255]
 [ 31  63  96 130 165 201 238 276 315 355]
 [ 41  83 126 170 215 261 308 356 405 455]
 [ 51 103 156 210 265 321 378 436 495 555]
 [ 61 123 186 250 315 381 448 516 585 655]
 [ 71 143 216 290 365 441 518 596 675 755]
 [ 81 163 246 330 415 501 588 676 765 855]
 [ 91 183 276 370 465 561 658 756 855 955]]


In [79]:
# na potrzeby kilku przykładów wykorzystamy kopię oryginalnej tablicy
arr_nan = arr.copy()

In [80]:
# filtrowanie tablicy zwraca tablicę boolowską - mapę - wartości, które spełniają i nie spełniają warunku
divide_by_five_map = (arr_nan % 5 == 0)
divide_by_five_map

array([[False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True]])

In [81]:
# będziemy też od czasu do czasu sprawdzać czy pracujemy na kopii czy widoku
# tu mamy do czynienia z tzw. fancy slicing - więc kopia
arrays_share_data(arr_nan, divide_by_five_map)

False

In [82]:
# taką tablicę możemy przyłożyć do innej tablicy (uwaga na wymiary!)
divide_by_five = arr_nan[divide_by_five_map]
divide_by_five

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [83]:
arrays_share_data(divide_by_five, arr_nan)

False

In [86]:
# zamieniamy wartości stojące na indeksach z mapy na wartość np.nan (not a number)
arr_nan[divide_by_five_map] = np.nan

In [87]:
arr_nan

array([[ 1.,  2.,  3.,  4., nan,  6.,  7.,  8.,  9., nan],
       [11., 12., 13., 14., nan, 16., 17., 18., 19., nan],
       [21., 22., 23., 24., nan, 26., 27., 28., 29., nan],
       [31., 32., 33., 34., nan, 36., 37., 38., 39., nan],
       [41., 42., 43., 44., nan, 46., 47., 48., 49., nan],
       [51., 52., 53., 54., nan, 56., 57., 58., 59., nan],
       [61., 62., 63., 64., nan, 66., 67., 68., 69., nan],
       [71., 72., 73., 74., nan, 76., 77., 78., 79., nan],
       [81., 82., 83., 84., nan, 86., 87., 88., 89., nan],
       [91., 92., 93., 94., nan, 96., 97., 98., 99., nan]])

In [85]:
# okazuje się, że dla typu np.int nie możemy tego zrobić
# może dla np.float
# po nieudanej operacji wstawienia nan należy sprawdzić czy tablica zawiera poprawne dane
# jeżeli nie to operację stworzenia kopii należy wykonać jeszcze raz
arr_nan = arr_nan.astype(np.float64)
arr_nan

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [ ]:
arr_nan[divide_by_five_map] = np.nan

In [90]:
# wykonajmy ponownie operację sumy
print(arr_nan.sum())

nan


In [91]:
print(arr_nan.sum(axis=0))
print(arr_nan.sum(axis=1))

[460. 470. 480. 490.  nan 510. 520. 530. 540.  nan]
[nan nan nan nan nan nan nan nan nan nan]


In [96]:
# jeżeli chcemy potraktować wartości nan w jakiś szczególny sposób, np. jako 0 (zero) to mamy do
# dyspozycji dedykowane funckje - tu sumy
print(np.nansum(arr_nan))
print(np.nansum(arr_nan, axis=0))
print(np.nansum(arr_nan, axis=1))

4000.0
[460. 470. 480. 490.   0. 510. 520. 530. 540.   0.]
[ 40. 120. 200. 280. 360. 440. 520. 600. 680. 760.]


In [103]:
# mnożenie elementów tablicy
# nie działa? dlaczego 0 ? Tu następuje przepełnienie wartości dla typów obsługiwanych przez numpy.
# Typ int wbudowany w Python może być niezwykle dużą liczbą (pamięć operacyjna nas ogranicza), ale  numpy
# opieramy się o typy znane z języka C. Przepełnienie wartości np.int64 czy np.float64 przy mnożeniu może
# nastąpić bardzo szybko. I tu zwracane jest 0 bez żadnego ostrzeżenia - trzeba o tym pamiętać.
print(arr.prod())
print(arr.prod(axis=0))

0
[  478015854767451  1242688846823424  2394832584543399  4060162871525376
  6393838623046875  9585618768101376 13865696119905399 19511273389031424
 26853950884211451 36288000000000000]


In [104]:
# numpy posiada bardzo wiele wbudowanych funkcji arytmetycznych, trygonometrycznych, algebry liniowej i innych.
# Algebrą liniową zajemy się nieco później. Poniżej kilka przykładów innych, popularnych operacji.
print(arr.max(), arr.max(axis=0))

100 [ 91  92  93  94  95  96  97  98  99 100]


In [107]:
# możemy również wykorzystać operacje tego typu do filtrowania tablicy
arr[(arr == arr.max(axis=0))]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [112]:
# tu warto przedstawić również funkcję np.where, która zamiast zwracać wartości spełniające warunek,
# może zwracać indeksy, na których te warunki są spełnione. Poniżej zobaczymy dwie tablice, gdyż talica, w
# której filtrujemy jest dwuwymiarowa. Pierwszy wymiar to wiersz, a drugi kolumna.
# Funkcja np.where przyjmuje do trzech argumentów: warunek, x, y. Jeżeli podany jest tylko warunek to zwraca indeksy elementów
# spełniających ten warunek.

In [175]:
np.where(arr == arr.max(axis=0))

(array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [114]:
# co jest ekwiwalentem 
np.asarray(arr == arr.max(axis=0)).nonzero()

(array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [115]:
# ale możemy ją wykorzystać również w taki sposób
# warunek, wartość jeżeli warunek spełniony, wartość jeżeli warunek nie jest spełniony
np.where(arr == arr.max(axis=0), arr, np.nan)

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

## 2. Moduł np.random

Moduł `np.random` dostarcza wielu funkcji, które pozwalają zarówno na tworzenie tablic wartości losowych (bardziej precyzyjnie to pseudo-losowych, ze zwględu na sposób działania komputerów) o określonych właściwościach, ale również na próbkowaniu z tablic już istniejących.

### 2.1 Tworzenie tablic z wykorzystaniem wybranych elementów modułu np.random

Korzystanie z modułu rozpoczynamy od inicjalizacji generatowa pseudolosowego.

In [118]:
rng = np.random.default_rng()

In [119]:
rng.random()

0.5105289144313383

In [120]:
rng.random((5,5))

array([[0.86223752, 0.09716792, 0.10049193, 0.63821181, 0.07994176],
       [0.43873571, 0.67147288, 0.88914129, 0.40594428, 0.84765291],
       [0.57873157, 0.28474806, 0.73737426, 0.27326699, 0.68629241],
       [0.49890538, 0.39065891, 0.08298539, 0.14877249, 0.8591022 ],
       [0.76125734, 0.97857083, 0.72785188, 0.88249304, 0.31856319]])

In [123]:
# wartości są zwracane z przedziału [0.0, 1.0)

In [128]:
# możemy próbkować wartości pseudolosowe z rozkładów, np. normalnego
# sygnatura tej funkcji: normal(loc=0.0, scale=1.0, size=None) (średnia, odchylenie standardowe, rozmiar)
print(rng.normal())
print(rng.normal(size=(5,5)))

0.40220661003806574
[[-0.1826277   1.92727089 -0.52373741 -1.06248931  1.42836312]
 [-0.50175243 -0.53240706  1.37864916 -1.54699275  0.98776891]
 [-1.33865617 -1.3971193   0.11285424  0.50387424 -0.81117727]
 [-0.94922863 -2.51051931 -1.52174994  0.06572507 -0.74872069]
 [ 0.32697    -0.24323032 -0.10784606 -0.0284671   0.02538068]]


In [129]:
# lub możemy użyć poniższej funkcji (mean=0.0, std=1.0)
rng.standard_normal(5)

array([-2.14948751,  0.21357562, -1.64945079,  0.36647586, -0.06227929])

In [131]:
# generowanie wartości całkowitych z przedziału
rng.integers(low=1, high=100, size=10)

array([80, 75, 76, 72, 26, 87, 91,  6, 48, 45])

In [ ]:
# choice - pobiera losową próbkę danych z tablicy
# sygnatura: choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
# Parametr p pozwala na przekazanie tablicy z rozkładem prawdopodobieństw

In [135]:
# zwróć uwagę na output: zwracany jest losowy wiersz
rng.choice(arr)

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [138]:
# domyślnie wybór odbywa się ze zwracaniem (replace=True)
rng.choice(arr, size=20)

array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60

In [140]:
rng.choice(arr, size=5, replace=False)

array([[51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [147]:
# a gdybyśmy jednak chcieli losować po pojedynczej wartości tablicy?
# możemy wykorzystać funkcje poznane w poprzednim labie
rng.choice(arr.flat, size=5, replace=False)

array([70, 68,  6, 21, 67])

In [149]:
# "tasowanie" tablicy odbywa się w trybie in-place
rng.shuffle(arr)
arr

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]])

In [152]:
# oraz domyślnie axis=0, ale możemy to zmienić
rng.shuffle(arr, axis=1)
arr

array([[ 43,  46,  47,  50,  41,  45,  49,  44,  42,  48],
       [ 23,  26,  27,  30,  21,  25,  29,  24,  22,  28],
       [ 83,  86,  87,  90,  81,  85,  89,  84,  82,  88],
       [ 63,  66,  67,  70,  61,  65,  69,  64,  62,  68],
       [ 53,  56,  57,  60,  51,  55,  59,  54,  52,  58],
       [  3,   6,   7,  10,   1,   5,   9,   4,   2,   8],
       [ 33,  36,  37,  40,  31,  35,  39,  34,  32,  38],
       [ 73,  76,  77,  80,  71,  75,  79,  74,  72,  78],
       [ 93,  96,  97, 100,  91,  95,  99,  94,  92,  98],
       [ 13,  16,  17,  20,  11,  15,  19,  14,  12,  18]])

In [154]:
# uzyskanie permutacji z tablicy lub podając integer (działa w wiekszości podobnych funkcji numpy)
# zwraca permutację liczb całkowitych z zakresu.
# Główna różnica między shuffle a permutation jest taka, iż pierwsza operacja odbywa się w trybie in-place
# a druga zwraca kopię
rng.permutation(10)

array([3, 0, 6, 8, 5, 4, 9, 1, 7, 2])

In [155]:
rng.permutation(arr)

array([[ 23,  26,  27,  30,  21,  25,  29,  24,  22,  28],
       [ 13,  16,  17,  20,  11,  15,  19,  14,  12,  18],
       [  3,   6,   7,  10,   1,   5,   9,   4,   2,   8],
       [ 93,  96,  97, 100,  91,  95,  99,  94,  92,  98],
       [ 43,  46,  47,  50,  41,  45,  49,  44,  42,  48],
       [ 83,  86,  87,  90,  81,  85,  89,  84,  82,  88],
       [ 73,  76,  77,  80,  71,  75,  79,  74,  72,  78],
       [ 63,  66,  67,  70,  61,  65,  69,  64,  62,  68],
       [ 53,  56,  57,  60,  51,  55,  59,  54,  52,  58],
       [ 33,  36,  37,  40,  31,  35,  39,  34,  32,  38]])

## 2.2 Zapis i odczyt tablic z plików

In [157]:
# zapisanie danych do pliku tekstowego
np.savetxt('arr.txt', arr)

In [161]:
# windows - odczyt zawartości zapomocą polecenia powłoki systemowej
!type arr.txt
# unix lub windows z WSL
# !cat arr.txt

4.300000000000000000e+01 4.600000000000000000e+01 4.700000000000000000e+01 5.000000000000000000e+01 4.100000000000000000e+01 4.500000000000000000e+01 4.900000000000000000e+01 4.400000000000000000e+01 4.200000000000000000e+01 4.800000000000000000e+01
2.300000000000000000e+01 2.600000000000000000e+01 2.700000000000000000e+01 3.000000000000000000e+01 2.100000000000000000e+01 2.500000000000000000e+01 2.900000000000000000e+01 2.400000000000000000e+01 2.200000000000000000e+01 2.800000000000000000e+01
8.300000000000000000e+01 8.600000000000000000e+01 8.700000000000000000e+01 9.000000000000000000e+01 8.100000000000000000e+01 8.500000000000000000e+01 8.900000000000000000e+01 8.400000000000000000e+01 8.200000000000000000e+01 8.800000000000000000e+01
6.300000000000000000e+01 6.600000000000000000e+01 6.700000000000000000e+01 7.000000000000000000e+01 6.100000000000000000e+01 6.500000000000000000e+01 6.900000000000000000e+01 6.400000000000000000e+01 6.200000000000000000e+01 6.800000000000000000e+01


In [162]:
# dodajemy format
np.savetxt('arr.txt', arr, fmt='%.3f')

In [163]:
!type arr.txt

43.000 46.000 47.000 50.000 41.000 45.000 49.000 44.000 42.000 48.000
23.000 26.000 27.000 30.000 21.000 25.000 29.000 24.000 22.000 28.000
83.000 86.000 87.000 90.000 81.000 85.000 89.000 84.000 82.000 88.000
63.000 66.000 67.000 70.000 61.000 65.000 69.000 64.000 62.000 68.000
53.000 56.000 57.000 60.000 51.000 55.000 59.000 54.000 52.000 58.000
3.000 6.000 7.000 10.000 1.000 5.000 9.000 4.000 2.000 8.000
33.000 36.000 37.000 40.000 31.000 35.000 39.000 34.000 32.000 38.000
73.000 76.000 77.000 80.000 71.000 75.000 79.000 74.000 72.000 78.000
93.000 96.000 97.000 100.000 91.000 95.000 99.000 94.000 92.000 98.000
13.000 16.000 17.000 20.000 11.000 15.000 19.000 14.000 12.000 18.000


In [164]:
# wczytanie danych z pliku (ta funkcja posiada wiele parametrów mających wpływ na sposób wczytywania danych)
arr_from_file = np.loadtxt('arr.txt')

In [167]:
print(arr_from_file, arr_from_file.dtype)

[[ 43.  46.  47.  50.  41.  45.  49.  44.  42.  48.]
 [ 23.  26.  27.  30.  21.  25.  29.  24.  22.  28.]
 [ 83.  86.  87.  90.  81.  85.  89.  84.  82.  88.]
 [ 63.  66.  67.  70.  61.  65.  69.  64.  62.  68.]
 [ 53.  56.  57.  60.  51.  55.  59.  54.  52.  58.]
 [  3.   6.   7.  10.   1.   5.   9.   4.   2.   8.]
 [ 33.  36.  37.  40.  31.  35.  39.  34.  32.  38.]
 [ 73.  76.  77.  80.  71.  75.  79.  74.  72.  78.]
 [ 93.  96.  97. 100.  91.  95.  99.  94.  92.  98.]
 [ 13.  16.  17.  20.  11.  15.  19.  14.  12.  18.]] float64


In [168]:
# ten format jest oczywiście wygodny dla człowieka i dane często są dostarczane w takiej formie
# jednak nie jest to sposób najbardziej wydajny z dostępnych.
# Tutaj pokażę tylko jedną z możliwości, ale dla poszerzenia wiedzy można zainteresować się formatami
# danych wykorzystywanymi w zagadnieniach Big Data.
np.save('arr_pickle', arr)

## Zadania


1. Stwórz tablicę o nazwie `a_small_one` o wymiarach 8x8 z wartościami od 1 do 64.

2. Dla tablicy `a_small_one` policz:
   * sumę dla każdej kolumny,
   * sumę skumulowaną dla każdego wiersza,
   * wartość średnią dla każdego wiersza,

3. Zwróć podtablicę z tablicy `a_small_one` z elementami parzystymi (nie nadpisuj tej zmiennej).

4. Zapisz do zmiennej o nazwie `no_even_small_one` tablicę `a_small_one` zamieniając wartości parzyste na wartość np.nan.

5. Dla tablicy `no_even_small_one` policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):
   * sumę dla każdego wiersza,
   * średnią dla każdej kolumny,
   * wartość najmniejszą i w całej tablicy,

6. Do tablicy `no_even_small_one` wstaw za pomocą funkcji `np.where`:

   * wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję `np.isnan()`)
   * liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy `a_small_one` - dla warunku wstawiaj wartość z `a_small_one` lub `no_even_small_one`

8. Stwórz tablicę o nazwie `sto_by_sto` o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

9. Dla tablicy `sto_by_sto` policz:
   * wartość średnią w każdym wierszu i kolumnie (oddzielnie),
   * policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast).

10. Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł `timeit`) porównaj czasy wykonania dla tej tablicy:
    * zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja `savez` w dokumentacji biblioteki numpy)
    * odczytu dla trzech wyżej wymienionych plików.