In [1]:
import numpy as np

### 1. Stwórz tablicę o nazwie a_small_one o wymiarach 8x8 z wartościami od 1 do 64.

In [2]:
a_small_one = np.arange(1,65).reshape(8,8)
a_small_one

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

### 2. Dla tablicy a_small_one policz:


*   sumę dla każdej kolumny,
* sumę skumulowaną dla każdego wiersza,
* wartość średnią dla każdego wiersza,
   



In [3]:
# Suma dla każdej kolumny
print(a_small_one.sum(axis=0))

[232 240 248 256 264 272 280 288]


In [4]:
# Suma skumulowana dla każdego wiersza
print(a_small_one.cumsum(axis=1))

[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]


In [5]:
# Wartość średnia dla każdego wiersza
print(a_small_one.mean(axis=1))


[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


### 3. Zwróć podtablicę z tablicy a_small_one z elementami parzystymi (nie nadpisuj tej zmiennej).

In [6]:
print(a_small_one[:,1::2])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]


### 4. Zapisz do zmiennej o nazwie no_even_small_one tablicę a_small_one zamieniając wartości parzyste na wartość np.nan.

In [7]:
even = (a_small_one % 2 == 0)
no_even_small_one = a_small_one.copy()
no_even_small_one = no_even_small_one.astype(float)
no_even_small_one[even] = np.nan
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

### 5. Dla tablicy no_even_small_one policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):

* sumę dla każdego wiersza,
* średnią dla każdej kolumny,
* wartość najmniejszą w całej tablicy,

In [8]:
# Suma dla każdego wiersza
print(np.nansum(no_even_small_one, axis=1))

[ 16.  48.  80. 112. 144. 176. 208. 240.]


In [33]:
# Średnia dla każdej kolumny
print(np.nanmean(no_even_small_one, axis= 0))

[29. 30. 31. 32. 33. 34. 35. 36.]


In [10]:
# Wartość najmniejszą i w całej tablicy
print(np.nanmin(no_even_small_one))

1.0


### 6. Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:

* wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())
* liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy a_small_one - dla warunku wstawiaj wartość z a_small_one lub no_even_small_one

In [11]:
# Wartości 1 dla każdej wartości np.nan
no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
no_even_small_one

array([[ 1.,  1.,  3.,  1.,  5.,  1.,  7.,  1.],
       [ 9.,  1., 11.,  1., 13.,  1., 15.,  1.],
       [17.,  1., 19.,  1., 21.,  1., 23.,  1.],
       [25.,  1., 27.,  1., 29.,  1., 31.,  1.],
       [33.,  1., 35.,  1., 37.,  1., 39.,  1.],
       [41.,  1., 43.,  1., 45.,  1., 47.,  1.],
       [49.,  1., 51.,  1., 53.,  1., 55.,  1.],
       [57.,  1., 59.,  1., 61.,  1., 63.,  1.]])

In [12]:
# Liczby parzyste
no_even_small_one = np.where(a_small_one > no_even_small_one, a_small_one, no_even_small_one)
no_even_small_one

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

### 7. Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

In [13]:
rng = np.random.default_rng()

In [14]:
sto_by_sto = rng.normal(size=(100,100))
sto_by_sto

array([[ 0.28372568, -2.2364163 ,  0.96323648, ...,  0.30440776,
         0.73752819,  0.69523455],
       [ 0.65823144,  0.76094324,  0.77441807, ...,  1.33348521,
        -0.6956907 , -1.73809418],
       [ 1.02229024,  0.784942  , -1.41726727, ..., -0.10662994,
         0.47105823,  1.13100364],
       ...,
       [-0.66039796, -0.85072126, -2.57478956, ...,  0.22917786,
         0.42086961,  0.4162342 ],
       [-0.80217173,  1.26781976,  0.16241225, ..., -0.93581079,
         0.61582402, -0.15729036],
       [ 2.03702054,  2.22322807,  1.1595897 , ...,  1.65859287,
        -0.37806352, -1.13990659]])

### 8. Dla tablicy sto_by_sto policz:

* wartość średnią w każdym wierszu i kolumnie (oddzielnie),
* policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast).

In [15]:
# Wartość średnia w każdym wierszu
mean_row = np.mean(sto_by_sto, axis=1)
mean_row

array([-0.09023513,  0.02078668, -0.10361843, -0.03864956,  0.06398744,
       -0.08631831,  0.11931684,  0.04855962,  0.02871872, -0.02837606,
       -0.05879088, -0.10190894,  0.25547632,  0.05936999,  0.0709716 ,
        0.16857144, -0.1894468 ,  0.10534075, -0.06945252, -0.03646382,
       -0.1063353 , -0.04323012,  0.03667931, -0.13820127, -0.00548433,
        0.1546168 ,  0.15313724, -0.2196547 ,  0.00396164, -0.05429551,
       -0.01576684,  0.03745696,  0.0667922 ,  0.05126655,  0.03258505,
       -0.01942779,  0.16252074,  0.05019594,  0.15642323,  0.08527475,
       -0.01319476,  0.02651395, -0.01226484, -0.0073587 , -0.07722379,
       -0.17735771, -0.03152099, -0.07970275, -0.02756363, -0.03163368,
       -0.00997551, -0.06977111,  0.08562554,  0.17488599, -0.01228576,
        0.12686729, -0.14148812, -0.07286679, -0.31427982, -0.11305267,
        0.14668081,  0.22140552, -0.03401643, -0.00770336, -0.00837815,
       -0.22936363, -0.21612534,  0.00777357,  0.02355045,  0.06

In [16]:
# Wartość średnia w każdej kolumnie
mean_col = np.mean(sto_by_sto, axis=0)
mean_col

array([ 4.02689609e-02,  9.47244409e-02, -1.44744334e-01, -7.95609339e-02,
       -2.31566489e-03, -1.04147237e-01, -1.59820167e-01, -9.62329403e-03,
       -1.05401759e-01,  1.43626438e-02, -1.88660694e-02,  2.39401013e-01,
        3.21900891e-02, -1.97225423e-01,  1.22576138e-01,  4.76697352e-02,
        4.19648855e-03,  3.00620747e-02,  1.67224775e-02, -2.59295576e-02,
        1.21597339e-02,  7.15519614e-03, -1.04416025e-01, -1.95708751e-01,
       -1.39134017e-01,  3.82567518e-02, -3.30577896e-02,  3.06061413e-02,
        1.74062070e-01, -3.54949254e-02,  7.43071223e-02, -1.17012416e-02,
       -1.55608568e-01, -1.86882801e-01,  1.19943728e-01, -2.76685666e-04,
        7.61111850e-02,  3.15495581e-02,  1.64466189e-02,  3.00521202e-01,
       -3.98420011e-02, -2.21542396e-01,  5.21954555e-02,  8.72924380e-02,
        1.01324493e-01, -9.15035856e-02, -1.10421874e-01, -1.12337980e-01,
        1.10936671e-02, -1.38187129e-03,  1.77878177e-04,  1.93118001e-02,
        9.17353864e-02,  

In [17]:
# Średnia różnica bezwzględna dla średniej z wierszy
print(np.mean(np.abs(mean_row)))

0.07994319895921467


In [18]:
# Średnia różnica bezwzględna dla średniej z kolumn
print(np.mean(np.abs(mean_col)))

0.08093795179122866


### 9. Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł timeit) porównaj czasy wykonania dla tej tablicy:

* zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja savez_compressed w dokumentacji biblioteki numpy)
* odczytu dla trzech wyżej wymienionych plików.

In [19]:
thousand = rng.normal(size=(1000, 1000))

In [20]:
from time import time

### Zapis

In [21]:
# Zapis do pliku tekstowego
start_time = time()
np.savetxt('thousand.txt', thousand)
end_time_txt = time() - start_time

In [22]:
# Zapis do pliku w formacie picle
start_time = time()
np.save('thousand_pickle', thousand)
end_time_picle = time() - start_time

In [23]:
# Zapis do pliku skompresowanego
start_time = time()
np.savez_compressed('thousand_compressed', thousand)
end_time_comp = time() - start_time

In [24]:
print(f"{end_time_txt} - Time for txt\n{end_time_picle} - Time for picle\n{end_time_comp} - Time for compressed file")

0.38524484634399414 - Time for txt
0.0015759468078613281 - Time for picle
0.22655892372131348 - Time for compressed file


### Odczyt

In [34]:
# Odczyt pliku tekstowego
start_time = time()
np.loadtxt('thousand.txt')
end_time_txt = time() - start_time

In [35]:
# Odczyt pliku w formacie picle
start_time = time()
np.load('thousand_pickle.npy')
end_time_picle = time() - start_time

In [36]:
# Odczyt do pliku skompresowanego
start_time = time()
np.load('thousand_compressed.npz')
end_time_comp = time() - start_time

In [37]:
print(f"{end_time_txt} - Time for txt\n{end_time_picle} - Time for picle\n{end_time_comp} - Time for compressed file")

0.1941678524017334 - Time for txt
0.0018858909606933594 - Time for picle
0.0004298686981201172 - Time for compressed file
