In [3]:
import numpy as np

### 1. Stwórz tablicę o nazwie a_small_one o wymiarach 8x8 z wartościami od 1 do 64.

In [4]:
a_small_one = np.arange(1,65).reshape(8,8)
a_small_one

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

### 2. Dla tablicy a_small_one policz:


*   sumę dla każdej kolumny,
* sumę skumulowaną dla każdego wiersza,
* wartość średnią dla każdego wiersza,
   



In [43]:
# Suma dla każdej kolumny
print(a_small_one.sum(axis=0))

[232 240 248 256 264 272 280 288]


In [44]:
# Suma skumulowana dla każdego wiersza
print(a_small_one.cumsum(axis=1))

[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]


In [7]:
# Wartość średnia dla każdego wiersza
print(a_small_one.mean(axis=1))


[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


### 3. Zwróć podtablicę z tablicy a_small_one z elementami parzystymi (nie nadpisuj tej zmiennej).

In [8]:
print(a_small_one[:,1::2])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [50 52 54 56]
 [58 60 62 64]]


### 4. Zapisz do zmiennej o nazwie no_even_small_one tablicę a_small_one zamieniając wartości parzyste na wartość np.nan.

In [9]:
even = (a_small_one % 2 == 0)
no_even_small_one = a_small_one.copy()
no_even_small_one = no_even_small_one.astype(float)
no_even_small_one[even] = np.nan
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

### 5. Dla tablicy no_even_small_one policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):

* sumę dla każdego wiersza,
* średnią dla każdej kolumny,
* wartość najmniejszą w całej tablicy,

In [45]:
# Suma dla każdego wiersza
print(np.nansum(no_even_small_one, axis=1))

[ 36. 100. 164. 228. 292. 356. 420. 484.]


In [46]:
# średnia dla każdej kolumny
print(np.nanmean(no_even_small_one, axis= 0))

[29. 30. 31. 32. 33. 34. 35. 36.]


In [12]:
# Wartość najmniejszą i w całej tablicy
print(np.nanmin(no_even_small_one))

1.0


### 6. Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:

* wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())
* liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy a_small_one - dla warunku wstawiaj wartość z a_small_one lub no_even_small_one

In [21]:
# Wartości 1 dla każdej wartości np.nan
no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
no_even_small_one

array([[ 1.,  1.,  3.,  1.,  5.,  1.,  7.,  1.],
       [ 9.,  1., 11.,  1., 13.,  1., 15.,  1.],
       [17.,  1., 19.,  1., 21.,  1., 23.,  1.],
       [25.,  1., 27.,  1., 29.,  1., 31.,  1.],
       [33.,  1., 35.,  1., 37.,  1., 39.,  1.],
       [41.,  1., 43.,  1., 45.,  1., 47.,  1.],
       [49.,  1., 51.,  1., 53.,  1., 55.,  1.],
       [57.,  1., 59.,  1., 61.,  1., 63.,  1.]])

In [22]:
# Liczby parzyste
no_even_small_one = np.where(a_small_one > no_even_small_one, a_small_one, no_even_small_one)
no_even_small_one

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

### 7. Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

In [13]:
rng = np.random.default_rng()

In [14]:
sto_by_sto = rng.normal(size=(100,100))
sto_by_sto

array([[ 0.07566934, -1.15291632,  0.14129953, ..., -1.59129842,
        -0.56926621,  0.08923535],
       [ 0.71069962, -0.68585608,  0.63144191, ...,  0.21140193,
         0.41540382,  0.13332266],
       [ 0.84156767,  0.53438223, -0.85521231, ..., -1.93592724,
        -0.50656012, -2.06337189],
       ...,
       [-0.41158762, -0.73176322, -0.11342814, ...,  0.09290286,
         0.66935513,  0.22411457],
       [-0.54004127, -1.36014725,  0.29500206, ..., -0.13558135,
         1.09292057,  0.07666958],
       [ 1.38249469,  0.39820065,  0.38694377, ...,  0.30190562,
        -1.28153225, -0.48699228]])

### 8. Dla tablicy sto_by_sto policz:

* wartość średnią w każdym wierszu i kolumnie (oddzielnie),
* policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast).

In [47]:
# Wartość średnia w każdym wierszu
mean_row = np.mean(sto_by_sto, axis=1)
mean_row

array([ 0.12462734, -0.02443559, -0.16252594,  0.18129859,  0.02128013,
       -0.13955731, -0.11238357,  0.10612001, -0.00484227, -0.11353601,
        0.04494254, -0.18224541, -0.00306621,  0.0220917 , -0.11941996,
        0.10715055, -0.02317992,  0.01358692,  0.05043196,  0.02274577,
        0.04608244,  0.05764908, -0.01685772,  0.00793966, -0.13459776,
        0.13040628, -0.0646291 , -0.18243147, -0.09750773, -0.0080061 ,
        0.0030682 ,  0.00181807,  0.13684794, -0.0663538 , -0.09045305,
        0.05358564, -0.13767491,  0.0373399 , -0.0231052 ,  0.01134909,
       -0.03292022, -0.03306103, -0.09445852,  0.05041933,  0.02641727,
       -0.05600915,  0.21012156, -0.00467007,  0.00555925,  0.08491691,
       -0.00663723, -0.0560861 ,  0.1659093 ,  0.12612242, -0.00787405,
       -0.0279724 ,  0.12682718, -0.01450377,  0.11101679, -0.14846526,
       -0.03463688, -0.06642453,  0.07382484, -0.02679459, -0.01529   ,
       -0.03122511, -0.01387178, -0.01483497,  0.08100632,  0.08

In [48]:
# Wartość średnia w każdej kolumnie
mean_col = np.mean(sto_by_sto, axis=0)
mean_col

array([ 1.71304543e-01,  5.83368012e-02, -5.64470814e-02,  3.82116662e-02,
        9.16770160e-02,  5.51758686e-03, -1.67050024e-01,  2.83271063e-03,
       -6.76519320e-02, -6.77344420e-02,  2.43580364e-02, -1.59376822e-01,
        8.96216536e-02, -7.51477823e-03, -8.82352688e-02, -2.50653602e-02,
       -3.70817374e-02,  8.94461849e-02, -8.14796950e-02,  2.68271316e-02,
        1.38091662e-02, -4.15549921e-02, -4.90578424e-02,  8.21511731e-03,
        7.41391405e-02,  3.11556700e-02,  1.16757786e-01, -1.38895802e-01,
        3.99520611e-02, -3.85878608e-02,  4.12395560e-02,  2.15741047e-03,
        6.97044840e-02, -1.21560085e-01,  3.85303138e-02,  5.35019007e-02,
        2.52517351e-01, -3.88301683e-02,  4.45353524e-02,  2.99517433e-01,
        3.68440414e-02,  1.74274859e-01,  1.30024564e-02, -1.17984799e-01,
       -1.24479093e-01,  4.57389759e-04, -1.17490211e-01, -9.12270963e-02,
       -1.21921970e-01,  1.33349940e-01, -5.29451541e-02, -3.45177277e-02,
       -4.54336226e-02,  

In [29]:
# Średnia różnica bezwzględna dla średniej z wierszy
print(np.mean(np.abs(mean_row)))

0.07068709873356692


In [30]:
# Średnia różnica bezwzględna dla średniej z kolumn
print(np.mean(np.abs(mean_col)))

0.07008948613779953


### 9. Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł timeit) porównaj czasy wykonania dla tej tablicy:

* zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja savez_compressed w dokumentacji biblioteki numpy)
* odczytu dla trzech wyżej wymienionych plików.

In [32]:
thousand = rng.normal(size=(1000, 1000))

In [34]:
from time import time

In [37]:
# Zapis do pliku tekstowego
start_time = time()
np.savetxt('thousand.txt', thousand)
end_time_txt = time() - start_time

In [39]:
# Zapis do pliku w formacie picle
start_time = time()
np.save('thousand_pickle', thousand)
end_time_picle = time() - start_time

In [40]:
# Zapis do pliku skompresowanego
start_time = time()
np.savez_compressed('thousand_compressed', thousand)
end_time_comp = time() - start_time

In [42]:
print(f"{end_time_txt} - Time for txt\n{end_time_picle} - Time for picle\n{end_time_comp} - Time for compressed file")

0.38864588737487793 - Time for txt
0.0019328594207763672 - Time for picle
0.2401881217956543 - Time for compressed file
